import "./globals.css";
import AuthButton from './components/AuthButton';
import ActionButtons from './components/ActionButtons'; // フッターのボタンをインポート

export const metadata = {
  title: "Be Happy♥",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Walter+Turncoat&family=Yomogi&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="antialiased">
        <AuthButton />
        {children}
        <footer className="w-full flex items-center justify-center p-4 bg-gray-100">
          <div className="min-h-[8vh] flex flex-col items-center justify-center p-4">
            <ActionButtons />
          </div>
        </footer>
      </body>
    </html>
  );
}
