import "./globals.css";
import AuthButton from './components/AuthButton';
import ActionButtons from './components/ActionButtons';

export const metadata = {
  title: "Be Happy♥",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Be Happy♥</title>
        <meta name="description" content="Generated by create next app" />
        <meta property="og:title" content="Be Happy♥" />
        <meta property="og:description" content="嫌な経験をAIがポジティブに変換する癒しのアプリ" />
        <meta property="og:image" content="/OGP.png" />  {/* ローカルのOGP画像を参照 */}
        <meta property="og:url" content="https://be-happy-front.vercel.app/" />
        <meta property="og:image" content="https://be-happy-front.vercel.app/OGP.png" />

        <meta property="og:type" content="website" />

        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:title" content="Be Happy♥" />
        <meta name="twitter:description" content="嫌な経験をAIがポジティブに変換する癒しのアプリ" />
        <meta name="twitter:image" content="https://yourwebsite.com/OGP.png" />

        <link
          href="https://fonts.googleapis.com/css2?family=Walter+Turncoat&family=Yomogi&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="antialiased">
        <AuthButton />
        {children}
        <footer className="w-full flex items-center justify-center p-4 bg-gray-100">
          <div className="min-h-[8vh] flex flex-col items-center justify-center p-4">
            <ActionButtons />
          </div>
        </footer>
      </body>
    </html>
  );
}
