import "./globals.css";
import AuthButton from './components/AuthButton';

export const metadata = {
  title: "Be Happy♥",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Walter+Turncoat&family=Yomogi&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="antialiased">
        <AuthButton />
        {children}
      </body>
    </html>
  );
}
