name: Trigger Parent Repository

on:
  push:
    branches:
      - main  # トリガーするブランチを指定

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger parent repository dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PARENT_REPO_TOKEN }}
          repository: erika-to-omochi/be-happy
          event-type: update-submodules
